//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Defines values for HealthChecksDatabase.
const (
	HealthChecksDatabaseError HealthChecksDatabase = "error"
	HealthChecksDatabaseOk    HealthChecksDatabase = "ok"
)

// Valid indicates whether the value is a known member of the HealthChecksDatabase enum.
func (e HealthChecksDatabase) Valid() bool {
	switch e {
	case HealthChecksDatabaseError:
		return true
	case HealthChecksDatabaseOk:
		return true
	default:
		return false
	}
}

// Defines values for HealthChecksMqtt.
const (
	Connected    HealthChecksMqtt = "connected"
	Disabled     HealthChecksMqtt = "disabled"
	Disconnected HealthChecksMqtt = "disconnected"
)

// Valid indicates whether the value is a known member of the HealthChecksMqtt enum.
func (e HealthChecksMqtt) Valid() bool {
	switch e {
	case Connected:
		return true
	case Disabled:
		return true
	case Disconnected:
		return true
	default:
		return false
	}
}

// Defines values for HealthLiveResponseStatus.
const (
	HealthLiveResponseStatusOk HealthLiveResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthLiveResponseStatus enum.
func (e HealthLiveResponseStatus) Valid() bool {
	switch e {
	case HealthLiveResponseStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for HealthReadyResponseStatus.
const (
	HealthReadyResponseStatusDegraded HealthReadyResponseStatus = "degraded"
	HealthReadyResponseStatusReady    HealthReadyResponseStatus = "ready"
	HealthReadyResponseStatusStarting HealthReadyResponseStatus = "starting"
)

// Valid indicates whether the value is a known member of the HealthReadyResponseStatus enum.
func (e HealthReadyResponseStatus) Valid() bool {
	switch e {
	case HealthReadyResponseStatusDegraded:
		return true
	case HealthReadyResponseStatusReady:
		return true
	case HealthReadyResponseStatusStarting:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusDegraded HealthResponseStatus = "degraded"
	HealthResponseStatusOk       HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case HealthResponseStatusDegraded:
		return true
	case HealthResponseStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for LogoutResponseStatus.
const (
	LoggedOut LogoutResponseStatus = "logged_out"
)

// Valid indicates whether the value is a known member of the LogoutResponseStatus enum.
func (e LogoutResponseStatus) Valid() bool {
	switch e {
	case LoggedOut:
		return true
	default:
		return false
	}
}

// Defines values for StatusOkStatus.
const (
	Ok StatusOkStatus = "ok"
)

// Valid indicates whether the value is a known member of the StatusOkStatus enum.
func (e StatusOkStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for TokenRevokedResponseStatus.
const (
	Revoked TokenRevokedResponseStatus = "revoked"
)

// Valid indicates whether the value is a known member of the TokenRevokedResponseStatus enum.
func (e TokenRevokedResponseStatus) Valid() bool {
	switch e {
	case Revoked:
		return true
	default:
		return false
	}
}

// AuthMeResponse defines model for AuthMeResponse.
type AuthMeResponse struct {
	CsrfToken *string    `json:"csrf_token,omitempty"`
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	Kind      string     `json:"kind"`
	Scopes    []string   `json:"scopes"`
	Username  string     `json:"username"`
}

// CameraHealthCheck defines model for CameraHealthCheck.
type CameraHealthCheck struct {
	Online int `json:"online"`
	Total  int `json:"total"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	CurrentPassword string `json:"current_password"`
	NewPassword     string `json:"new_password"`
}

// CreateTokenRequest defines model for CreateTokenRequest.
type CreateTokenRequest struct {
	Name   string    `json:"name"`
	Scopes *[]string `json:"scopes,omitempty"`
}

// CreateTokenResponse defines model for CreateTokenResponse.
type CreateTokenResponse struct {
	CreatedAt   time.Time `json:"created_at"`
	Id          int64     `json:"id"`
	Name        string    `json:"name"`
	Scopes      []string  `json:"scopes"`
	Token       string    `json:"token"`
	TokenPrefix string    `json:"token_prefix"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// HealthChecks defines model for HealthChecks.
type HealthChecks struct {
	Cameras  CameraHealthCheck    `json:"cameras"`
	Database HealthChecksDatabase `json:"database"`
	Mqtt     HealthChecksMqtt     `json:"mqtt"`
	Storage  StorageHealthCheck   `json:"storage"`
}

// HealthChecksDatabase defines model for HealthChecks.Database.
type HealthChecksDatabase string

// HealthChecksMqtt defines model for HealthChecks.Mqtt.
type HealthChecksMqtt string

// HealthLiveResponse defines model for HealthLiveResponse.
type HealthLiveResponse struct {
	Status HealthLiveResponseStatus `json:"status"`
	Uptime string                   `json:"uptime"`
}

// HealthLiveResponseStatus defines model for HealthLiveResponse.Status.
type HealthLiveResponseStatus string

// HealthReadyResponse defines model for HealthReadyResponse.
type HealthReadyResponse struct {
	Checks ReadyChecks               `json:"checks"`
	Status HealthReadyResponseStatus `json:"status"`
}

// HealthReadyResponseStatus defines model for HealthReadyResponse.Status.
type HealthReadyResponseStatus string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Checks  HealthChecks         `json:"checks"`
	Status  HealthResponseStatus `json:"status"`
	Uptime  string               `json:"uptime"`
	Version string               `json:"version"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Remember *bool  `json:"remember,omitempty"`
	Username string `json:"username"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	CsrfToken string    `json:"csrf_token"`
	ExpiresAt time.Time `json:"expires_at"`
	Kind      string    `json:"kind"`
	Username  string    `json:"username"`
}

// LogoutResponse defines model for LogoutResponse.
type LogoutResponse struct {
	Status LogoutResponseStatus `json:"status"`
}

// LogoutResponseStatus defines model for LogoutResponse.Status.
type LogoutResponseStatus string

// ReadyCameraCheck defines model for ReadyCameraCheck.
type ReadyCameraCheck struct {
	Degraded int `json:"degraded"`
	Total    int `json:"total"`
}

// ReadyChecks defines model for ReadyChecks.
type ReadyChecks struct {
	Cameras     ReadyCameraCheck   `json:"cameras"`
	Database    string             `json:"database"`
	Initialized bool               `json:"initialized"`
	Storage     *ReadyStorageCheck `json:"storage,omitempty"`
}

// ReadyStorageCheck defines model for ReadyStorageCheck.
type ReadyStorageCheck struct {
	DiskLow         *bool `json:"disk_low,omitempty"`
	RecordingPaused *bool `json:"recording_paused,omitempty"`
}

// RecompressionStats defines model for RecompressionStats.
type RecompressionStats struct {
	BytesReclaimed       int64      `json:"bytes_reclaimed"`
	Enabled              bool       `json:"enabled"`
	LastRun              *time.Time `json:"last_run,omitempty"`
	SegmentsRecompressed int        `json:"segments_recompressed"`
}

// StatusOk defines model for StatusOk.
type StatusOk struct {
	Status StatusOkStatus `json:"status"`
}

// StatusOkStatus defines model for StatusOk.Status.
type StatusOkStatus string

// StorageHealthCheck defines model for StorageHealthCheck.
type StorageHealthCheck struct {
	DiskAvailable   string             `json:"disk_available"`
	DiskLow         bool               `json:"disk_low"`
	Recompression   RecompressionStats `json:"recompression"`
	RecordingPaused bool               `json:"recording_paused"`
	Used            string             `json:"used"`
	UsedBytes       int64              `json:"used_bytes"`
}

// SystemResponse defines model for SystemResponse.
type SystemResponse struct {
	Cameras      int    `json:"cameras"`
	Decoder      string `json:"decoder"`
	Online       int    `json:"online"`
	Storage      string `json:"storage"`
	StorageBytes int64  `json:"storage_bytes"`
	Uptime       string `json:"uptime"`
	Version      string `json:"version"`
}

// TokenRevokedResponse defines model for TokenRevokedResponse.
type TokenRevokedResponse struct {
	Status TokenRevokedResponseStatus `json:"status"`
}

// TokenRevokedResponseStatus defines model for TokenRevokedResponse.Status.
type TokenRevokedResponseStatus string

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// CreateTokenJSONRequestBody defines body for CreateToken for application/json ContentType.
type CreateTokenJSONRequestBody = CreateTokenRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Change the current user's password
	// (POST /api/auth/change-password)
	ChangePassword(w http.ResponseWriter, r *http.Request)
	// Authenticate with username and password
	// (POST /api/auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// End the current session
	// (POST /api/auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Get the current authenticated principal
	// (GET /api/auth/me)
	GetAuthMe(w http.ResponseWriter, r *http.Request)
	// Full health check
	// (GET /api/health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Liveness probe
	// (GET /api/health/live)
	GetHealthLive(w http.ResponseWriter, r *http.Request)
	// Readiness probe
	// (GET /api/health/ready)
	GetHealthReady(w http.ResponseWriter, r *http.Request)
	// OpenAPI specification
	// (GET /api/openapi.json)
	GetOpenAPISpec(w http.ResponseWriter, r *http.Request)
	// System information
	// (GET /api/system)
	GetSystem(w http.ResponseWriter, r *http.Request)
	// Trigger manual recompression
	// (POST /api/system/recompress/trigger)
	TriggerRecompression(w http.ResponseWriter, r *http.Request)
	// Create a new API token
	// (POST /api/tokens)
	CreateToken(w http.ResponseWriter, r *http.Request)
	// Revoke an API token
	// (DELETE /api/tokens/{id})
	DeleteToken(w http.ResponseWriter, r *http.Request, id int64)
	// Prometheus metrics
	// (GET /metrics)
	GetMetrics(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ChangePassword operation middleware
func (siw *ServerInterfaceWrapper) ChangePassword(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChangePassword(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthMe operation middleware
func (siw *ServerInterfaceWrapper) GetAuthMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthLive operation middleware
func (siw *ServerInterfaceWrapper) GetHealthLive(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthLive(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthReady operation middleware
func (siw *ServerInterfaceWrapper) GetHealthReady(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthReady(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOpenAPISpec operation middleware
func (siw *ServerInterfaceWrapper) GetOpenAPISpec(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOpenAPISpec(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSystem operation middleware
func (siw *ServerInterfaceWrapper) GetSystem(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSystem(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerRecompression operation middleware
func (siw *ServerInterfaceWrapper) TriggerRecompression(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerRecompression(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateToken operation middleware
func (siw *ServerInterfaceWrapper) CreateToken(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteToken operation middleware
func (siw *ServerInterfaceWrapper) DeleteToken(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteToken(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMetrics operation middleware
func (siw *ServerInterfaceWrapper) GetMetrics(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMetrics(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/api/auth/change-password", wrapper.ChangePassword)
	m.HandleFunc("POST "+options.BaseURL+"/api/auth/login", wrapper.Login)
	m.HandleFunc("POST "+options.BaseURL+"/api/auth/logout", wrapper.Logout)
	m.HandleFunc("GET "+options.BaseURL+"/api/auth/me", wrapper.GetAuthMe)
	m.HandleFunc("GET "+options.BaseURL+"/api/health", wrapper.GetHealth)
	m.HandleFunc("GET "+options.BaseURL+"/api/health/live", wrapper.GetHealthLive)
	m.HandleFunc("GET "+options.BaseURL+"/api/health/ready", wrapper.GetHealthReady)
	m.HandleFunc("GET "+options.BaseURL+"/api/openapi.json", wrapper.GetOpenAPISpec)
	m.HandleFunc("GET "+options.BaseURL+"/api/system", wrapper.GetSystem)
	m.HandleFunc("POST "+options.BaseURL+"/api/system/recompress/trigger", wrapper.TriggerRecompression)
	m.HandleFunc("POST "+options.BaseURL+"/api/tokens", wrapper.CreateToken)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/tokens/{id}", wrapper.DeleteToken)
	m.HandleFunc("GET "+options.BaseURL+"/metrics", wrapper.GetMetrics)

	return m
}

type ChangePasswordRequestObject struct {
	Body *ChangePasswordJSONRequestBody
}

type ChangePasswordResponseObject interface {
	VisitChangePasswordResponse(w http.ResponseWriter) error
}

type ChangePassword200JSONResponse StatusOk

func (response ChangePassword200JSONResponse) VisitChangePasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ChangePassword400JSONResponse Error

func (response ChangePassword400JSONResponse) VisitChangePasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse LoginResponse

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Login401JSONResponse Error

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type Login429JSONResponse Error

func (response Login429JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout200JSONResponse LogoutResponse

func (response Logout200JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAuthMeRequestObject struct {
}

type GetAuthMeResponseObject interface {
	VisitGetAuthMeResponse(w http.ResponseWriter) error
}

type GetAuthMe200JSONResponse AuthMeResponse

func (response GetAuthMe200JSONResponse) VisitGetAuthMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAuthMe401JSONResponse Error

func (response GetAuthMe401JSONResponse) VisitGetAuthMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthLiveRequestObject struct {
}

type GetHealthLiveResponseObject interface {
	VisitGetHealthLiveResponse(w http.ResponseWriter) error
}

type GetHealthLive200JSONResponse HealthLiveResponse

func (response GetHealthLive200JSONResponse) VisitGetHealthLiveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthReadyRequestObject struct {
}

type GetHealthReadyResponseObject interface {
	VisitGetHealthReadyResponse(w http.ResponseWriter) error
}

type GetHealthReady200JSONResponse HealthReadyResponse

func (response GetHealthReady200JSONResponse) VisitGetHealthReadyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthReady503JSONResponse HealthReadyResponse

func (response GetHealthReady503JSONResponse) VisitGetHealthReadyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type GetOpenAPISpecRequestObject struct {
}

type GetOpenAPISpecResponseObject interface {
	VisitGetOpenAPISpecResponse(w http.ResponseWriter) error
}

type GetOpenAPISpec200JSONResponse map[string]interface{}

func (response GetOpenAPISpec200JSONResponse) VisitGetOpenAPISpecResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSystemRequestObject struct {
}

type GetSystemResponseObject interface {
	VisitGetSystemResponse(w http.ResponseWriter) error
}

type GetSystem200JSONResponse SystemResponse

func (response GetSystem200JSONResponse) VisitGetSystemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type TriggerRecompressionRequestObject struct {
}

type TriggerRecompressionResponseObject interface {
	VisitTriggerRecompressionResponse(w http.ResponseWriter) error
}

type TriggerRecompression202Response struct {
}

func (response TriggerRecompression202Response) VisitTriggerRecompressionResponse(w http.ResponseWriter) error {
	w.WriteHeader(202)
	return nil
}

type TriggerRecompression409TextResponse string

func (response TriggerRecompression409TextResponse) VisitTriggerRecompressionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(409)

	_, err := w.Write([]byte(response))
	return err
}

type CreateTokenRequestObject struct {
	Body *CreateTokenJSONRequestBody
}

type CreateTokenResponseObject interface {
	VisitCreateTokenResponse(w http.ResponseWriter) error
}

type CreateToken201JSONResponse CreateTokenResponse

func (response CreateToken201JSONResponse) VisitCreateTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateToken400JSONResponse Error

func (response CreateToken400JSONResponse) VisitCreateTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTokenRequestObject struct {
	Id int64 `json:"id"`
}

type DeleteTokenResponseObject interface {
	VisitDeleteTokenResponse(w http.ResponseWriter) error
}

type DeleteToken200JSONResponse TokenRevokedResponse

func (response DeleteToken200JSONResponse) VisitDeleteTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMetricsRequestObject struct {
}

type GetMetricsResponseObject interface {
	VisitGetMetricsResponse(w http.ResponseWriter) error
}

type GetMetrics200TextResponse string

func (response GetMetrics200TextResponse) VisitGetMetricsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(response))
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Change the current user's password
	// (POST /api/auth/change-password)
	ChangePassword(ctx context.Context, request ChangePasswordRequestObject) (ChangePasswordResponseObject, error)
	// Authenticate with username and password
	// (POST /api/auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// End the current session
	// (POST /api/auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Get the current authenticated principal
	// (GET /api/auth/me)
	GetAuthMe(ctx context.Context, request GetAuthMeRequestObject) (GetAuthMeResponseObject, error)
	// Full health check
	// (GET /api/health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// Liveness probe
	// (GET /api/health/live)
	GetHealthLive(ctx context.Context, request GetHealthLiveRequestObject) (GetHealthLiveResponseObject, error)
	// Readiness probe
	// (GET /api/health/ready)
	GetHealthReady(ctx context.Context, request GetHealthReadyRequestObject) (GetHealthReadyResponseObject, error)
	// OpenAPI specification
	// (GET /api/openapi.json)
	GetOpenAPISpec(ctx context.Context, request GetOpenAPISpecRequestObject) (GetOpenAPISpecResponseObject, error)
	// System information
	// (GET /api/system)
	GetSystem(ctx context.Context, request GetSystemRequestObject) (GetSystemResponseObject, error)
	// Trigger manual recompression
	// (POST /api/system/recompress/trigger)
	TriggerRecompression(ctx context.Context, request TriggerRecompressionRequestObject) (TriggerRecompressionResponseObject, error)
	// Create a new API token
	// (POST /api/tokens)
	CreateToken(ctx context.Context, request CreateTokenRequestObject) (CreateTokenResponseObject, error)
	// Revoke an API token
	// (DELETE /api/tokens/{id})
	DeleteToken(ctx context.Context, request DeleteTokenRequestObject) (DeleteTokenResponseObject, error)
	// Prometheus metrics
	// (GET /metrics)
	GetMetrics(ctx context.Context, request GetMetricsRequestObject) (GetMetricsResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ChangePassword operation middleware
func (sh *strictHandler) ChangePassword(w http.ResponseWriter, r *http.Request) {
	var request ChangePasswordRequestObject

	var body ChangePasswordJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ChangePassword(ctx, request.(ChangePasswordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ChangePassword")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ChangePasswordResponseObject); ok {
		if err := validResponse.VisitChangePasswordResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAuthMe operation middleware
func (sh *strictHandler) GetAuthMe(w http.ResponseWriter, r *http.Request) {
	var request GetAuthMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuthMe(ctx, request.(GetAuthMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuthMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAuthMeResponseObject); ok {
		if err := validResponse.VisitGetAuthMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealthLive operation middleware
func (sh *strictHandler) GetHealthLive(w http.ResponseWriter, r *http.Request) {
	var request GetHealthLiveRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthLive(ctx, request.(GetHealthLiveRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthLive")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthLiveResponseObject); ok {
		if err := validResponse.VisitGetHealthLiveResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealthReady operation middleware
func (sh *strictHandler) GetHealthReady(w http.ResponseWriter, r *http.Request) {
	var request GetHealthReadyRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthReady(ctx, request.(GetHealthReadyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthReady")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthReadyResponseObject); ok {
		if err := validResponse.VisitGetHealthReadyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOpenAPISpec operation middleware
func (sh *strictHandler) GetOpenAPISpec(w http.ResponseWriter, r *http.Request) {
	var request GetOpenAPISpecRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOpenAPISpec(ctx, request.(GetOpenAPISpecRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOpenAPISpec")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOpenAPISpecResponseObject); ok {
		if err := validResponse.VisitGetOpenAPISpecResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSystem operation middleware
func (sh *strictHandler) GetSystem(w http.ResponseWriter, r *http.Request) {
	var request GetSystemRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSystem(ctx, request.(GetSystemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSystem")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSystemResponseObject); ok {
		if err := validResponse.VisitGetSystemResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TriggerRecompression operation middleware
func (sh *strictHandler) TriggerRecompression(w http.ResponseWriter, r *http.Request) {
	var request TriggerRecompressionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TriggerRecompression(ctx, request.(TriggerRecompressionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TriggerRecompression")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TriggerRecompressionResponseObject); ok {
		if err := validResponse.VisitTriggerRecompressionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateToken operation middleware
func (sh *strictHandler) CreateToken(w http.ResponseWriter, r *http.Request) {
	var request CreateTokenRequestObject

	var body CreateTokenJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateToken(ctx, request.(CreateTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateTokenResponseObject); ok {
		if err := validResponse.VisitCreateTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteToken operation middleware
func (sh *strictHandler) DeleteToken(w http.ResponseWriter, r *http.Request, id int64) {
	var request DeleteTokenRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteToken(ctx, request.(DeleteTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteTokenResponseObject); ok {
		if err := validResponse.VisitDeleteTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMetrics operation middleware
func (sh *strictHandler) GetMetrics(w http.ResponseWriter, r *http.Request) {
	var request GetMetricsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMetrics(ctx, request.(GetMetricsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMetrics")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMetricsResponseObject); ok {
		if err := validResponse.VisitGetMetricsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xZWXPbvhH/Khi0M33h33KOdqZ6c9M0cZvDY2f84vFoYHJFISIBBljKUT367h0cvEFK",
	"PpTmTSIXwG93f9iLDzSWeSEFCNR0/kB1vIKc2Z9nJa4+wyXoQgoN5kmhZAEKOdj3sVbLBco1CPMPtwXQ",
	"OdWouEjpLqLws+AK9IKheb2UKje/aMIQ/kCeA42Ga9ZcJMHNdCwLdypHyHVQxj9gSrGt+V9qUILlEBDe",
	"RVTBj5IrSOj8ppH0COrzbutd5d13iNFs+47loNhHYBmu3q0gXg8tI0XGRftcLhBSUBalRJaFXvUwObmo",
	"2iuIZMVEChdM63upkkv4UYLGgJ9KpUDgovCCQeMJuJ8S6IEbbNnbIIhWAUP4ZvgyCnXEXU/xfw+x3Xkv",
	"rFGqW6HkUVzmSUeWC/zb20auxYgXVNrQa+w+2jeLQsGS/9zvYW596u6E27O3Qw0valsnZOH3Skk1tClU",
	"j6eBOLHQvq0rqAMus9fU/vyzgiWd0z/NmlA383FuNrzNu8j4ld0xRwQQZW5wyDWNBmAa6+Y/ENvisRQC",
	"YgRjxoTr3l92l0ES3EejVCyFfbCvnFgHd89wtRIeXFSbpDll3Kyf+GYi9GtkWOqeeULqlIW9Hnu97Des",
	"F4wDuwSWbCduak2HKfPZTTxzrNH76igjYA3FFBrAEU0gVSwJum1MGQ9mSpnn6dG5AkFFLG0noE+4KKIb",
	"UJpL8Qj3edjN0kmPfpIpH08Gk/lKQQ75HbQDyJ2UGTDx5NQ/mb081N+hFnpOXdPC2UE1orIs8TFBIJNp",
	"CslClnjwJQkd7G6nDVYjBVZN6BcpsQLXow/meUlmoFAvxwxrB8GRs4z/t6Nii+AHpgl7sM8V4SzRPilq",
	"54xKtVGbdLYdeojr9SKT92H4CmKpEi7SRcFKHVZyFzzYKKlAm9hyhQwDPrnbIuiFgjhjPIdDizAQLicH",
	"4WZM40KV4vDLqyHNjScMDo84zNZ+teNhjO0QDdQL+efK3q2v6ycn7sPvaqAQCXOBbRjPjHJBwu+nS+32",
	"/ZwfcORAxtnQOhpzk4U1/UF8GsbharU/I+obpWWCANi+CYKe2GqEfCJFNbFqSP8EYpmACuo+1c224tBY",
	"KfsIs71MMTIoPRr12jWwV6uPc7o49n3iRq4heUxmVG7JM66aDSpxqThurwzTfbADpkCdlbiqhzeW0vZx",
	"Y+EVYmHgx1KuOVTiXNC5f1Q1e3OqPcWa1rLg/wHTUNu8tJQu/+pY8QKtP+jZxTlZSkVyJljKRUq8kSMC",
	"G3M1I1ITWkeEiYQ4pUgCCLHZhHBBcAXkGhJAZOQL4L1Ua3LNE5Dk0q4GdWJAcTQhhNaS15fk7OK8VXHO",
	"6enJq5NTy9wCBCs4ndM39pGp8XBlDTdjBZ+xElez2E5R/mhXm4V09ajxKTP4zhM6741bqPMbaPyHTLb2",
	"gkmBIOxCVhQZj+3S2XftSOvi095+NDjT2XVpgqoE+8AR0Cr0+vT0xUDU+cOe23V2BY04uyXGzm9f8Gw3",
	"LQgcfM0yntgdCXiZiOoyz5na1t6xLPLTKWLK379o0hpSIUu1uWXG8fTWbNDwIDMV/rj3bQNwJKd3+qBf",
	"7OtuYxOwuxUguoxj0HpZZs7hr47v8HOxMS4nsYIEhKlSbSZ/+/rvxz/7kiGQjOccDcNbsZfOb27btDOx",
	"1ICLzYJ7jitSNV020B3OPdM0TZHPvD8uDdrNXpgHKSTE4OjevPci6Vy7VgaZUNll+RQC2n4AdN8ejqlw",
	"7+tGQOF3Xp9CcRHzgmXEpr9fRf8vEglrsSvpmf0DYMfsHdkG9LgbVrZmn/KCq+qP6YXeGCxgBidBfF3U",
	"NcG/yiwjTg1iJ08tZb12fXVnGd/Afp0/Gamj690ZsgZ0vwK14TEQrgmzuKcikdlMgNakUPIODrCEm3Hu",
	"NcWlH4UenQPtue60MRzyXUT/evrm/whDSKygTPjF7MgPc4yvV08q4GOO+VqAOLs4vyogfq5j+l3GQN9v",
	"KyD+PKILiAnT5N9XX79M6txewJf+9Jbm9ovIBtS2pby2/euU2q7DPSYVez10yP1WwmeCTjBqvTFtblfh",
	"gaudtrOmrZ+h4mnqWvBwEfDNCXTmG0NjvB72Z50VxH7SqOr2fimF8BNnRcZ4mCZ10zosmDpnsMzeC9PW",
	"FUqm5nHPWl4Z0zOWLCOqp9So3ezsWk80ac3n3GN1aMPv2AeV7K+Og2CcqlaA+I+zv02bZuEQRgTcm8ad",
	"1B+Xw0WK8/fsgSc7R+wMEIZu/6d9Xrm9YIrlgKDMjn7OYTr/ZsrBq/698VjU0nz/gO/2iFEoOGQadXA1",
	"Wura2S0nTOwzcg6oeKyn4u5nL7JX5SdHjwslc8AVlJpUeLrqBARCQaKbkrrjsZvbXfTQmYDd3Bo3alCb",
	"iimlyuiczqh57ncfDLuaMptLEVXdjh9s1cbWDdessc3Zw6lZnQft4kTGZQ4Cq+Th1zfJcrjJx1bxqyOi",
	"mxzk8DTG8pt5W+1ud/8LAAD//6m2z7j6JQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
