//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Defines values for HealthChecksDatabase.
const (
	HealthChecksDatabaseError HealthChecksDatabase = "error"
	HealthChecksDatabaseOk    HealthChecksDatabase = "ok"
)

// Valid indicates whether the value is a known member of the HealthChecksDatabase enum.
func (e HealthChecksDatabase) Valid() bool {
	switch e {
	case HealthChecksDatabaseError:
		return true
	case HealthChecksDatabaseOk:
		return true
	default:
		return false
	}
}

// Defines values for HealthChecksMqtt.
const (
	Connected    HealthChecksMqtt = "connected"
	Disabled     HealthChecksMqtt = "disabled"
	Disconnected HealthChecksMqtt = "disconnected"
)

// Valid indicates whether the value is a known member of the HealthChecksMqtt enum.
func (e HealthChecksMqtt) Valid() bool {
	switch e {
	case Connected:
		return true
	case Disabled:
		return true
	case Disconnected:
		return true
	default:
		return false
	}
}

// Defines values for HealthLiveResponseStatus.
const (
	HealthLiveResponseStatusOk HealthLiveResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthLiveResponseStatus enum.
func (e HealthLiveResponseStatus) Valid() bool {
	switch e {
	case HealthLiveResponseStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for HealthReadyResponseStatus.
const (
	HealthReadyResponseStatusDegraded HealthReadyResponseStatus = "degraded"
	HealthReadyResponseStatusReady    HealthReadyResponseStatus = "ready"
	HealthReadyResponseStatusStarting HealthReadyResponseStatus = "starting"
)

// Valid indicates whether the value is a known member of the HealthReadyResponseStatus enum.
func (e HealthReadyResponseStatus) Valid() bool {
	switch e {
	case HealthReadyResponseStatusDegraded:
		return true
	case HealthReadyResponseStatusReady:
		return true
	case HealthReadyResponseStatusStarting:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusDegraded HealthResponseStatus = "degraded"
	HealthResponseStatusOk       HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case HealthResponseStatusDegraded:
		return true
	case HealthResponseStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for LogoutResponseStatus.
const (
	LoggedOut LogoutResponseStatus = "logged_out"
)

// Valid indicates whether the value is a known member of the LogoutResponseStatus enum.
func (e LogoutResponseStatus) Valid() bool {
	switch e {
	case LoggedOut:
		return true
	default:
		return false
	}
}

// Defines values for PTZRequestAction.
const (
	Move PTZRequestAction = "move"
	Stop PTZRequestAction = "stop"
	Zoom PTZRequestAction = "zoom"
)

// Valid indicates whether the value is a known member of the PTZRequestAction enum.
func (e PTZRequestAction) Valid() bool {
	switch e {
	case Move:
		return true
	case Stop:
		return true
	case Zoom:
		return true
	default:
		return false
	}
}

// Defines values for PTZRequestDirection.
const (
	Down  PTZRequestDirection = "down"
	In    PTZRequestDirection = "in"
	Left  PTZRequestDirection = "left"
	Out   PTZRequestDirection = "out"
	Right PTZRequestDirection = "right"
	Up    PTZRequestDirection = "up"
)

// Valid indicates whether the value is a known member of the PTZRequestDirection enum.
func (e PTZRequestDirection) Valid() bool {
	switch e {
	case Down:
		return true
	case In:
		return true
	case Left:
		return true
	case Out:
		return true
	case Right:
		return true
	case Up:
		return true
	default:
		return false
	}
}

// Defines values for StatusDeletedStatus.
const (
	Deleted StatusDeletedStatus = "deleted"
)

// Valid indicates whether the value is a known member of the StatusDeletedStatus enum.
func (e StatusDeletedStatus) Valid() bool {
	switch e {
	case Deleted:
		return true
	default:
		return false
	}
}

// Defines values for StatusOkStatus.
const (
	Ok StatusOkStatus = "ok"
)

// Valid indicates whether the value is a known member of the StatusOkStatus enum.
func (e StatusOkStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for TokenRevokedResponseStatus.
const (
	Revoked TokenRevokedResponseStatus = "revoked"
)

// Valid indicates whether the value is a known member of the TokenRevokedResponseStatus enum.
func (e TokenRevokedResponseStatus) Valid() bool {
	switch e {
	case Revoked:
		return true
	default:
		return false
	}
}

// AuthMeResponse defines model for AuthMeResponse.
type AuthMeResponse struct {
	CsrfToken *string    `json:"csrf_token,omitempty"`
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	Kind      string     `json:"kind"`
	Scopes    []string   `json:"scopes"`
	Username  string     `json:"username"`
}

// CameraDetail defines model for CameraDetail.
type CameraDetail struct {
	Degraded       bool       `json:"degraded"`
	DegradedReason *string    `json:"degraded_reason,omitempty"`
	HasMotion      bool       `json:"has_motion"`
	LastFrame      *time.Time `json:"last_frame,omitempty"`
	Name           string     `json:"name"`
	Online         bool       `json:"online"`
	Ptz            bool       `json:"ptz"`
	Recording      bool       `json:"recording"`
	ZoneCount      int        `json:"zone_count"`
}

// CameraHealthCheck defines model for CameraHealthCheck.
type CameraHealthCheck struct {
	Online int `json:"online"`
	Total  int `json:"total"`
}

// CameraInfo defines model for CameraInfo.
type CameraInfo struct {
	HasMotion bool   `json:"has_motion"`
	Name      string `json:"name"`
	Online    bool   `json:"online"`
	Ptz       bool   `json:"ptz"`
}

// CameraListEnvelope defines model for CameraListEnvelope.
type CameraListEnvelope struct {
	HasMore bool         `json:"has_more"`
	Items   []CameraInfo `json:"items"`
	Limit   int          `json:"limit"`
	Offset  int          `json:"offset"`
	Total   int          `json:"total"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	CurrentPassword string `json:"current_password"`
	NewPassword     string `json:"new_password"`
}

// CreateTokenRequest defines model for CreateTokenRequest.
type CreateTokenRequest struct {
	Name   string    `json:"name"`
	Scopes *[]string `json:"scopes,omitempty"`
}

// CreateTokenResponse defines model for CreateTokenResponse.
type CreateTokenResponse struct {
	CreatedAt   time.Time `json:"created_at"`
	Id          int64     `json:"id"`
	Name        string    `json:"name"`
	Scopes      []string  `json:"scopes"`
	Token       string    `json:"token"`
	TokenPrefix string    `json:"token_prefix"`
}

// CreateZoneRequest defines model for CreateZoneRequest.
type CreateZoneRequest struct {
	Enabled         *bool        `json:"enabled,omitempty"`
	FaceRecognition *bool        `json:"face_recognition,omitempty"`
	Labels          *[]string    `json:"labels,omitempty"`
	Name            string       `json:"name"`
	Points          *[][]float32 `json:"points,omitempty"`
	TrackPresence   *bool        `json:"track_presence,omitempty"`
	X1              *float32     `json:"x1,omitempty"`
	X2              *float32     `json:"x2,omitempty"`
	Y1              *float32     `json:"y1,omitempty"`
	Y2              *float32     `json:"y2,omitempty"`
}

// DoorbellResponse defines model for DoorbellResponse.
type DoorbellResponse struct {
	Camera  string `json:"camera"`
	EventId string `json:"event_id"`
	Person  string `json:"person"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// HealthChecks defines model for HealthChecks.
type HealthChecks struct {
	Cameras  CameraHealthCheck    `json:"cameras"`
	Database HealthChecksDatabase `json:"database"`
	Mqtt     HealthChecksMqtt     `json:"mqtt"`
	Storage  StorageHealthCheck   `json:"storage"`
}

// HealthChecksDatabase defines model for HealthChecks.Database.
type HealthChecksDatabase string

// HealthChecksMqtt defines model for HealthChecks.Mqtt.
type HealthChecksMqtt string

// HealthLiveResponse defines model for HealthLiveResponse.
type HealthLiveResponse struct {
	Status HealthLiveResponseStatus `json:"status"`
	Uptime string                   `json:"uptime"`
}

// HealthLiveResponseStatus defines model for HealthLiveResponse.Status.
type HealthLiveResponseStatus string

// HealthReadyResponse defines model for HealthReadyResponse.
type HealthReadyResponse struct {
	Checks ReadyChecks               `json:"checks"`
	Status HealthReadyResponseStatus `json:"status"`
}

// HealthReadyResponseStatus defines model for HealthReadyResponse.Status.
type HealthReadyResponseStatus string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Checks  HealthChecks         `json:"checks"`
	Status  HealthResponseStatus `json:"status"`
	Uptime  string               `json:"uptime"`
	Version string               `json:"version"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Remember *bool  `json:"remember,omitempty"`
	Username string `json:"username"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	CsrfToken string    `json:"csrf_token"`
	ExpiresAt time.Time `json:"expires_at"`
	Kind      string    `json:"kind"`
	Username  string    `json:"username"`
}

// LogoutResponse defines model for LogoutResponse.
type LogoutResponse struct {
	Status LogoutResponseStatus `json:"status"`
}

// LogoutResponseStatus defines model for LogoutResponse.Status.
type LogoutResponseStatus string

// PTZRequest defines model for PTZRequest.
type PTZRequest struct {
	Action    PTZRequestAction     `json:"action"`
	Direction *PTZRequestDirection `json:"direction,omitempty"`
}

// PTZRequestAction defines model for PTZRequest.Action.
type PTZRequestAction string

// PTZRequestDirection defines model for PTZRequest.Direction.
type PTZRequestDirection string

// ReadyCameraCheck defines model for ReadyCameraCheck.
type ReadyCameraCheck struct {
	Degraded int `json:"degraded"`
	Total    int `json:"total"`
}

// ReadyChecks defines model for ReadyChecks.
type ReadyChecks struct {
	Cameras     ReadyCameraCheck   `json:"cameras"`
	Database    string             `json:"database"`
	Initialized bool               `json:"initialized"`
	Storage     *ReadyStorageCheck `json:"storage,omitempty"`
}

// ReadyStorageCheck defines model for ReadyStorageCheck.
type ReadyStorageCheck struct {
	DiskLow         *bool `json:"disk_low,omitempty"`
	RecordingPaused *bool `json:"recording_paused,omitempty"`
}

// RecompressionStats defines model for RecompressionStats.
type RecompressionStats struct {
	BytesReclaimed       int64      `json:"bytes_reclaimed"`
	Enabled              bool       `json:"enabled"`
	LastRun              *time.Time `json:"last_run,omitempty"`
	SegmentsRecompressed int        `json:"segments_recompressed"`
}

// StatusDeleted defines model for StatusDeleted.
type StatusDeleted struct {
	Status StatusDeletedStatus `json:"status"`
}

// StatusDeletedStatus defines model for StatusDeleted.Status.
type StatusDeletedStatus string

// StatusOk defines model for StatusOk.
type StatusOk struct {
	Status StatusOkStatus `json:"status"`
}

// StatusOkStatus defines model for StatusOk.Status.
type StatusOkStatus string

// StorageHealthCheck defines model for StorageHealthCheck.
type StorageHealthCheck struct {
	DiskAvailable   string             `json:"disk_available"`
	DiskLow         bool               `json:"disk_low"`
	Recompression   RecompressionStats `json:"recompression"`
	RecordingPaused bool               `json:"recording_paused"`
	Used            string             `json:"used"`
	UsedBytes       int64              `json:"used_bytes"`
}

// SystemResponse defines model for SystemResponse.
type SystemResponse struct {
	Cameras      int    `json:"cameras"`
	Decoder      string `json:"decoder"`
	Online       int    `json:"online"`
	Storage      string `json:"storage"`
	StorageBytes int64  `json:"storage_bytes"`
	Uptime       string `json:"uptime"`
	Version      string `json:"version"`
}

// TokenRevokedResponse defines model for TokenRevokedResponse.
type TokenRevokedResponse struct {
	Status TokenRevokedResponseStatus `json:"status"`
}

// TokenRevokedResponseStatus defines model for TokenRevokedResponse.Status.
type TokenRevokedResponseStatus string

// Zone defines model for Zone.
type Zone struct {
	Camera          string      `json:"camera"`
	Enabled         bool        `json:"enabled"`
	FaceRecognition bool        `json:"face_recognition"`
	Id              int         `json:"id"`
	Labels          []string    `json:"labels"`
	Name            string      `json:"name"`
	Points          [][]float32 `json:"points"`
	TrackPresence   bool        `json:"track_presence"`
}

// ZonePresence defines model for ZonePresence.
type ZonePresence struct {
	Label       string     `json:"label"`
	LastChanged *time.Time `json:"last_changed,omitempty"`
	LastSeen    *time.Time `json:"last_seen,omitempty"`
	Present     bool       `json:"present"`
	ZoneId      int        `json:"zone_id"`
}

// GetCameraThumbnailParams defines parameters for GetCameraThumbnail.
type GetCameraThumbnailParams struct {
	T time.Time `form:"t" json:"t"`
}

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// SendPTZCommandJSONRequestBody defines body for SendPTZCommand for application/json ContentType.
type SendPTZCommandJSONRequestBody = PTZRequest

// CreateZoneJSONRequestBody defines body for CreateZone for application/json ContentType.
type CreateZoneJSONRequestBody = CreateZoneRequest

// UpdateZoneJSONRequestBody defines body for UpdateZone for application/json ContentType.
type UpdateZoneJSONRequestBody = CreateZoneRequest

// CreateTokenJSONRequestBody defines body for CreateToken for application/json ContentType.
type CreateTokenJSONRequestBody = CreateTokenRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Change the current user's password
	// (POST /api/auth/change-password)
	ChangePassword(w http.ResponseWriter, r *http.Request)
	// Authenticate with username and password
	// (POST /api/auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// End the current session
	// (POST /api/auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Get the current authenticated principal
	// (GET /api/auth/me)
	GetAuthMe(w http.ResponseWriter, r *http.Request)
	// List all cameras
	// (GET /api/cameras)
	ListCameras(w http.ResponseWriter, r *http.Request)
	// Get camera detail
	// (GET /api/cameras/{name})
	GetCamera(w http.ResponseWriter, r *http.Request, name string)
	// Trigger a doorbell press event
	// (POST /api/cameras/{name}/doorbell)
	PressDoorbell(w http.ResponseWriter, r *http.Request, name string)
	// Send a PTZ command to a camera
	// (POST /api/cameras/{name}/ptz)
	SendPTZCommand(w http.ResponseWriter, r *http.Request, name string)
	// Get live camera snapshot
	// (GET /api/cameras/{name}/snapshot)
	GetCameraSnapshot(w http.ResponseWriter, r *http.Request, name string)
	// Get recording thumbnail at a given time
	// (GET /api/cameras/{name}/thumbnail)
	GetCameraThumbnail(w http.ResponseWriter, r *http.Request, name string, params GetCameraThumbnailParams)
	// List zones for a camera
	// (GET /api/cameras/{name}/zones)
	ListZones(w http.ResponseWriter, r *http.Request, name string)
	// Create a zone for a camera
	// (POST /api/cameras/{name}/zones)
	CreateZone(w http.ResponseWriter, r *http.Request, name string)
	// Delete a zone
	// (DELETE /api/cameras/{name}/zones/{zone})
	DeleteZone(w http.ResponseWriter, r *http.Request, name string, zone string)
	// Update a zone
	// (PUT /api/cameras/{name}/zones/{zone})
	UpdateZone(w http.ResponseWriter, r *http.Request, name string, zone string)
	// Get presence state for a zone
	// (GET /api/cameras/{name}/zones/{zone}/presence)
	GetZonePresence(w http.ResponseWriter, r *http.Request, name string, zone string)
	// Full health check
	// (GET /api/health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Liveness probe
	// (GET /api/health/live)
	GetHealthLive(w http.ResponseWriter, r *http.Request)
	// Readiness probe
	// (GET /api/health/ready)
	GetHealthReady(w http.ResponseWriter, r *http.Request)
	// OpenAPI specification
	// (GET /api/openapi.json)
	GetOpenAPISpec(w http.ResponseWriter, r *http.Request)
	// System information
	// (GET /api/system)
	GetSystem(w http.ResponseWriter, r *http.Request)
	// Trigger manual recompression
	// (POST /api/system/recompress/trigger)
	TriggerRecompression(w http.ResponseWriter, r *http.Request)
	// Create a new API token
	// (POST /api/tokens)
	CreateToken(w http.ResponseWriter, r *http.Request)
	// Revoke an API token
	// (DELETE /api/tokens/{id})
	DeleteToken(w http.ResponseWriter, r *http.Request, id int64)
	// Prometheus metrics
	// (GET /metrics)
	GetMetrics(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ChangePassword operation middleware
func (siw *ServerInterfaceWrapper) ChangePassword(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChangePassword(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthMe operation middleware
func (siw *ServerInterfaceWrapper) GetAuthMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCameras operation middleware
func (siw *ServerInterfaceWrapper) ListCameras(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCameras(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCamera operation middleware
func (siw *ServerInterfaceWrapper) GetCamera(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCamera(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PressDoorbell operation middleware
func (siw *ServerInterfaceWrapper) PressDoorbell(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PressDoorbell(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendPTZCommand operation middleware
func (siw *ServerInterfaceWrapper) SendPTZCommand(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendPTZCommand(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCameraSnapshot operation middleware
func (siw *ServerInterfaceWrapper) GetCameraSnapshot(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCameraSnapshot(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCameraThumbnail operation middleware
func (siw *ServerInterfaceWrapper) GetCameraThumbnail(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCameraThumbnailParams

	// ------------- Required query parameter "t" -------------

	if paramValue := r.URL.Query().Get("t"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "t"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "t", r.URL.Query(), &params.T, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "t", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCameraThumbnail(w, r, name, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListZones operation middleware
func (siw *ServerInterfaceWrapper) ListZones(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListZones(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateZone operation middleware
func (siw *ServerInterfaceWrapper) CreateZone(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateZone(w, r, name)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteZone operation middleware
func (siw *ServerInterfaceWrapper) DeleteZone(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// ------------- Path parameter "zone" -------------
	var zone string

	err = runtime.BindStyledParameterWithOptions("simple", "zone", r.PathValue("zone"), &zone, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "zone", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteZone(w, r, name, zone)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateZone operation middleware
func (siw *ServerInterfaceWrapper) UpdateZone(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// ------------- Path parameter "zone" -------------
	var zone string

	err = runtime.BindStyledParameterWithOptions("simple", "zone", r.PathValue("zone"), &zone, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "zone", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateZone(w, r, name, zone)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetZonePresence operation middleware
func (siw *ServerInterfaceWrapper) GetZonePresence(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// ------------- Path parameter "zone" -------------
	var zone string

	err = runtime.BindStyledParameterWithOptions("simple", "zone", r.PathValue("zone"), &zone, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "zone", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetZonePresence(w, r, name, zone)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthLive operation middleware
func (siw *ServerInterfaceWrapper) GetHealthLive(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthLive(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthReady operation middleware
func (siw *ServerInterfaceWrapper) GetHealthReady(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthReady(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOpenAPISpec operation middleware
func (siw *ServerInterfaceWrapper) GetOpenAPISpec(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOpenAPISpec(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSystem operation middleware
func (siw *ServerInterfaceWrapper) GetSystem(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSystem(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerRecompression operation middleware
func (siw *ServerInterfaceWrapper) TriggerRecompression(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerRecompression(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateToken operation middleware
func (siw *ServerInterfaceWrapper) CreateToken(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteToken operation middleware
func (siw *ServerInterfaceWrapper) DeleteToken(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteToken(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMetrics operation middleware
func (siw *ServerInterfaceWrapper) GetMetrics(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMetrics(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/api/auth/change-password", wrapper.ChangePassword)
	m.HandleFunc("POST "+options.BaseURL+"/api/auth/login", wrapper.Login)
	m.HandleFunc("POST "+options.BaseURL+"/api/auth/logout", wrapper.Logout)
	m.HandleFunc("GET "+options.BaseURL+"/api/auth/me", wrapper.GetAuthMe)
	m.HandleFunc("GET "+options.BaseURL+"/api/cameras", wrapper.ListCameras)
	m.HandleFunc("GET "+options.BaseURL+"/api/cameras/{name}", wrapper.GetCamera)
	m.HandleFunc("POST "+options.BaseURL+"/api/cameras/{name}/doorbell", wrapper.PressDoorbell)
	m.HandleFunc("POST "+options.BaseURL+"/api/cameras/{name}/ptz", wrapper.SendPTZCommand)
	m.HandleFunc("GET "+options.BaseURL+"/api/cameras/{name}/snapshot", wrapper.GetCameraSnapshot)
	m.HandleFunc("GET "+options.BaseURL+"/api/cameras/{name}/thumbnail", wrapper.GetCameraThumbnail)
	m.HandleFunc("GET "+options.BaseURL+"/api/cameras/{name}/zones", wrapper.ListZones)
	m.HandleFunc("POST "+options.BaseURL+"/api/cameras/{name}/zones", wrapper.CreateZone)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/cameras/{name}/zones/{zone}", wrapper.DeleteZone)
	m.HandleFunc("PUT "+options.BaseURL+"/api/cameras/{name}/zones/{zone}", wrapper.UpdateZone)
	m.HandleFunc("GET "+options.BaseURL+"/api/cameras/{name}/zones/{zone}/presence", wrapper.GetZonePresence)
	m.HandleFunc("GET "+options.BaseURL+"/api/health", wrapper.GetHealth)
	m.HandleFunc("GET "+options.BaseURL+"/api/health/live", wrapper.GetHealthLive)
	m.HandleFunc("GET "+options.BaseURL+"/api/health/ready", wrapper.GetHealthReady)
	m.HandleFunc("GET "+options.BaseURL+"/api/openapi.json", wrapper.GetOpenAPISpec)
	m.HandleFunc("GET "+options.BaseURL+"/api/system", wrapper.GetSystem)
	m.HandleFunc("POST "+options.BaseURL+"/api/system/recompress/trigger", wrapper.TriggerRecompression)
	m.HandleFunc("POST "+options.BaseURL+"/api/tokens", wrapper.CreateToken)
	m.HandleFunc("DELETE "+options.BaseURL+"/api/tokens/{id}", wrapper.DeleteToken)
	m.HandleFunc("GET "+options.BaseURL+"/metrics", wrapper.GetMetrics)

	return m
}

type ChangePasswordRequestObject struct {
	Body *ChangePasswordJSONRequestBody
}

type ChangePasswordResponseObject interface {
	VisitChangePasswordResponse(w http.ResponseWriter) error
}

type ChangePassword200JSONResponse StatusOk

func (response ChangePassword200JSONResponse) VisitChangePasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ChangePassword400JSONResponse Error

func (response ChangePassword400JSONResponse) VisitChangePasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse LoginResponse

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Login401JSONResponse Error

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type Login429JSONResponse Error

func (response Login429JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout200JSONResponse LogoutResponse

func (response Logout200JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAuthMeRequestObject struct {
}

type GetAuthMeResponseObject interface {
	VisitGetAuthMeResponse(w http.ResponseWriter) error
}

type GetAuthMe200JSONResponse AuthMeResponse

func (response GetAuthMe200JSONResponse) VisitGetAuthMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAuthMe401JSONResponse Error

func (response GetAuthMe401JSONResponse) VisitGetAuthMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListCamerasRequestObject struct {
}

type ListCamerasResponseObject interface {
	VisitListCamerasResponse(w http.ResponseWriter) error
}

type ListCameras200JSONResponse CameraListEnvelope

func (response ListCameras200JSONResponse) VisitListCamerasResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCameraRequestObject struct {
	Name string `json:"name"`
}

type GetCameraResponseObject interface {
	VisitGetCameraResponse(w http.ResponseWriter) error
}

type GetCamera200JSONResponse CameraDetail

func (response GetCamera200JSONResponse) VisitGetCameraResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCamera404JSONResponse Error

func (response GetCamera404JSONResponse) VisitGetCameraResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PressDoorbellRequestObject struct {
	Name string `json:"name"`
}

type PressDoorbellResponseObject interface {
	VisitPressDoorbellResponse(w http.ResponseWriter) error
}

type PressDoorbell200JSONResponse DoorbellResponse

func (response PressDoorbell200JSONResponse) VisitPressDoorbellResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PressDoorbell404JSONResponse Error

func (response PressDoorbell404JSONResponse) VisitPressDoorbellResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PressDoorbell503JSONResponse Error

func (response PressDoorbell503JSONResponse) VisitPressDoorbellResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type SendPTZCommandRequestObject struct {
	Name string `json:"name"`
	Body *SendPTZCommandJSONRequestBody
}

type SendPTZCommandResponseObject interface {
	VisitSendPTZCommandResponse(w http.ResponseWriter) error
}

type SendPTZCommand200JSONResponse StatusOk

func (response SendPTZCommand200JSONResponse) VisitSendPTZCommandResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SendPTZCommand400JSONResponse Error

func (response SendPTZCommand400JSONResponse) VisitSendPTZCommandResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SendPTZCommand404JSONResponse Error

func (response SendPTZCommand404JSONResponse) VisitSendPTZCommandResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetCameraSnapshotRequestObject struct {
	Name string `json:"name"`
}

type GetCameraSnapshotResponseObject interface {
	VisitGetCameraSnapshotResponse(w http.ResponseWriter) error
}

type GetCameraSnapshot200ImagejpegResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetCameraSnapshot200ImagejpegResponse) VisitGetCameraSnapshotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "image/jpeg")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetCameraSnapshot404JSONResponse Error

func (response GetCameraSnapshot404JSONResponse) VisitGetCameraSnapshotResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetCameraThumbnailRequestObject struct {
	Name   string `json:"name"`
	Params GetCameraThumbnailParams
}

type GetCameraThumbnailResponseObject interface {
	VisitGetCameraThumbnailResponse(w http.ResponseWriter) error
}

type GetCameraThumbnail200ImagejpegResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetCameraThumbnail200ImagejpegResponse) VisitGetCameraThumbnailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "image/jpeg")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetCameraThumbnail400JSONResponse Error

func (response GetCameraThumbnail400JSONResponse) VisitGetCameraThumbnailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetCameraThumbnail404JSONResponse Error

func (response GetCameraThumbnail404JSONResponse) VisitGetCameraThumbnailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListZonesRequestObject struct {
	Name string `json:"name"`
}

type ListZonesResponseObject interface {
	VisitListZonesResponse(w http.ResponseWriter) error
}

type ListZones200JSONResponse []Zone

func (response ListZones200JSONResponse) VisitListZonesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListZones404JSONResponse Error

func (response ListZones404JSONResponse) VisitListZonesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateZoneRequestObject struct {
	Name string `json:"name"`
	Body *CreateZoneJSONRequestBody
}

type CreateZoneResponseObject interface {
	VisitCreateZoneResponse(w http.ResponseWriter) error
}

type CreateZone201JSONResponse Zone

func (response CreateZone201JSONResponse) VisitCreateZoneResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateZone400JSONResponse Error

func (response CreateZone400JSONResponse) VisitCreateZoneResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateZone404JSONResponse Error

func (response CreateZone404JSONResponse) VisitCreateZoneResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteZoneRequestObject struct {
	Name string `json:"name"`
	Zone string `json:"zone"`
}

type DeleteZoneResponseObject interface {
	VisitDeleteZoneResponse(w http.ResponseWriter) error
}

type DeleteZone200JSONResponse StatusDeleted

func (response DeleteZone200JSONResponse) VisitDeleteZoneResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteZone404JSONResponse Error

func (response DeleteZone404JSONResponse) VisitDeleteZoneResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateZoneRequestObject struct {
	Name string `json:"name"`
	Zone string `json:"zone"`
	Body *UpdateZoneJSONRequestBody
}

type UpdateZoneResponseObject interface {
	VisitUpdateZoneResponse(w http.ResponseWriter) error
}

type UpdateZone200JSONResponse Zone

func (response UpdateZone200JSONResponse) VisitUpdateZoneResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateZone400JSONResponse Error

func (response UpdateZone400JSONResponse) VisitUpdateZoneResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateZone404JSONResponse Error

func (response UpdateZone404JSONResponse) VisitUpdateZoneResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetZonePresenceRequestObject struct {
	Name string `json:"name"`
	Zone string `json:"zone"`
}

type GetZonePresenceResponseObject interface {
	VisitGetZonePresenceResponse(w http.ResponseWriter) error
}

type GetZonePresence200JSONResponse []ZonePresence

func (response GetZonePresence200JSONResponse) VisitGetZonePresenceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetZonePresence404JSONResponse Error

func (response GetZonePresence404JSONResponse) VisitGetZonePresenceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthLiveRequestObject struct {
}

type GetHealthLiveResponseObject interface {
	VisitGetHealthLiveResponse(w http.ResponseWriter) error
}

type GetHealthLive200JSONResponse HealthLiveResponse

func (response GetHealthLive200JSONResponse) VisitGetHealthLiveResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthReadyRequestObject struct {
}

type GetHealthReadyResponseObject interface {
	VisitGetHealthReadyResponse(w http.ResponseWriter) error
}

type GetHealthReady200JSONResponse HealthReadyResponse

func (response GetHealthReady200JSONResponse) VisitGetHealthReadyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthReady503JSONResponse HealthReadyResponse

func (response GetHealthReady503JSONResponse) VisitGetHealthReadyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type GetOpenAPISpecRequestObject struct {
}

type GetOpenAPISpecResponseObject interface {
	VisitGetOpenAPISpecResponse(w http.ResponseWriter) error
}

type GetOpenAPISpec200JSONResponse map[string]interface{}

func (response GetOpenAPISpec200JSONResponse) VisitGetOpenAPISpecResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSystemRequestObject struct {
}

type GetSystemResponseObject interface {
	VisitGetSystemResponse(w http.ResponseWriter) error
}

type GetSystem200JSONResponse SystemResponse

func (response GetSystem200JSONResponse) VisitGetSystemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type TriggerRecompressionRequestObject struct {
}

type TriggerRecompressionResponseObject interface {
	VisitTriggerRecompressionResponse(w http.ResponseWriter) error
}

type TriggerRecompression202Response struct {
}

func (response TriggerRecompression202Response) VisitTriggerRecompressionResponse(w http.ResponseWriter) error {
	w.WriteHeader(202)
	return nil
}

type TriggerRecompression409TextResponse string

func (response TriggerRecompression409TextResponse) VisitTriggerRecompressionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(409)

	_, err := w.Write([]byte(response))
	return err
}

type CreateTokenRequestObject struct {
	Body *CreateTokenJSONRequestBody
}

type CreateTokenResponseObject interface {
	VisitCreateTokenResponse(w http.ResponseWriter) error
}

type CreateToken201JSONResponse CreateTokenResponse

func (response CreateToken201JSONResponse) VisitCreateTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateToken400JSONResponse Error

func (response CreateToken400JSONResponse) VisitCreateTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTokenRequestObject struct {
	Id int64 `json:"id"`
}

type DeleteTokenResponseObject interface {
	VisitDeleteTokenResponse(w http.ResponseWriter) error
}

type DeleteToken200JSONResponse TokenRevokedResponse

func (response DeleteToken200JSONResponse) VisitDeleteTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetMetricsRequestObject struct {
}

type GetMetricsResponseObject interface {
	VisitGetMetricsResponse(w http.ResponseWriter) error
}

type GetMetrics200TextResponse string

func (response GetMetrics200TextResponse) VisitGetMetricsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/plain")
	w.WriteHeader(200)

	_, err := w.Write([]byte(response))
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Change the current user's password
	// (POST /api/auth/change-password)
	ChangePassword(ctx context.Context, request ChangePasswordRequestObject) (ChangePasswordResponseObject, error)
	// Authenticate with username and password
	// (POST /api/auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// End the current session
	// (POST /api/auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Get the current authenticated principal
	// (GET /api/auth/me)
	GetAuthMe(ctx context.Context, request GetAuthMeRequestObject) (GetAuthMeResponseObject, error)
	// List all cameras
	// (GET /api/cameras)
	ListCameras(ctx context.Context, request ListCamerasRequestObject) (ListCamerasResponseObject, error)
	// Get camera detail
	// (GET /api/cameras/{name})
	GetCamera(ctx context.Context, request GetCameraRequestObject) (GetCameraResponseObject, error)
	// Trigger a doorbell press event
	// (POST /api/cameras/{name}/doorbell)
	PressDoorbell(ctx context.Context, request PressDoorbellRequestObject) (PressDoorbellResponseObject, error)
	// Send a PTZ command to a camera
	// (POST /api/cameras/{name}/ptz)
	SendPTZCommand(ctx context.Context, request SendPTZCommandRequestObject) (SendPTZCommandResponseObject, error)
	// Get live camera snapshot
	// (GET /api/cameras/{name}/snapshot)
	GetCameraSnapshot(ctx context.Context, request GetCameraSnapshotRequestObject) (GetCameraSnapshotResponseObject, error)
	// Get recording thumbnail at a given time
	// (GET /api/cameras/{name}/thumbnail)
	GetCameraThumbnail(ctx context.Context, request GetCameraThumbnailRequestObject) (GetCameraThumbnailResponseObject, error)
	// List zones for a camera
	// (GET /api/cameras/{name}/zones)
	ListZones(ctx context.Context, request ListZonesRequestObject) (ListZonesResponseObject, error)
	// Create a zone for a camera
	// (POST /api/cameras/{name}/zones)
	CreateZone(ctx context.Context, request CreateZoneRequestObject) (CreateZoneResponseObject, error)
	// Delete a zone
	// (DELETE /api/cameras/{name}/zones/{zone})
	DeleteZone(ctx context.Context, request DeleteZoneRequestObject) (DeleteZoneResponseObject, error)
	// Update a zone
	// (PUT /api/cameras/{name}/zones/{zone})
	UpdateZone(ctx context.Context, request UpdateZoneRequestObject) (UpdateZoneResponseObject, error)
	// Get presence state for a zone
	// (GET /api/cameras/{name}/zones/{zone}/presence)
	GetZonePresence(ctx context.Context, request GetZonePresenceRequestObject) (GetZonePresenceResponseObject, error)
	// Full health check
	// (GET /api/health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// Liveness probe
	// (GET /api/health/live)
	GetHealthLive(ctx context.Context, request GetHealthLiveRequestObject) (GetHealthLiveResponseObject, error)
	// Readiness probe
	// (GET /api/health/ready)
	GetHealthReady(ctx context.Context, request GetHealthReadyRequestObject) (GetHealthReadyResponseObject, error)
	// OpenAPI specification
	// (GET /api/openapi.json)
	GetOpenAPISpec(ctx context.Context, request GetOpenAPISpecRequestObject) (GetOpenAPISpecResponseObject, error)
	// System information
	// (GET /api/system)
	GetSystem(ctx context.Context, request GetSystemRequestObject) (GetSystemResponseObject, error)
	// Trigger manual recompression
	// (POST /api/system/recompress/trigger)
	TriggerRecompression(ctx context.Context, request TriggerRecompressionRequestObject) (TriggerRecompressionResponseObject, error)
	// Create a new API token
	// (POST /api/tokens)
	CreateToken(ctx context.Context, request CreateTokenRequestObject) (CreateTokenResponseObject, error)
	// Revoke an API token
	// (DELETE /api/tokens/{id})
	DeleteToken(ctx context.Context, request DeleteTokenRequestObject) (DeleteTokenResponseObject, error)
	// Prometheus metrics
	// (GET /metrics)
	GetMetrics(ctx context.Context, request GetMetricsRequestObject) (GetMetricsResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ChangePassword operation middleware
func (sh *strictHandler) ChangePassword(w http.ResponseWriter, r *http.Request) {
	var request ChangePasswordRequestObject

	var body ChangePasswordJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ChangePassword(ctx, request.(ChangePasswordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ChangePassword")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ChangePasswordResponseObject); ok {
		if err := validResponse.VisitChangePasswordResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAuthMe operation middleware
func (sh *strictHandler) GetAuthMe(w http.ResponseWriter, r *http.Request) {
	var request GetAuthMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuthMe(ctx, request.(GetAuthMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuthMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAuthMeResponseObject); ok {
		if err := validResponse.VisitGetAuthMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListCameras operation middleware
func (sh *strictHandler) ListCameras(w http.ResponseWriter, r *http.Request) {
	var request ListCamerasRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCameras(ctx, request.(ListCamerasRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCameras")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCamerasResponseObject); ok {
		if err := validResponse.VisitListCamerasResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCamera operation middleware
func (sh *strictHandler) GetCamera(w http.ResponseWriter, r *http.Request, name string) {
	var request GetCameraRequestObject

	request.Name = name

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCamera(ctx, request.(GetCameraRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCamera")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCameraResponseObject); ok {
		if err := validResponse.VisitGetCameraResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PressDoorbell operation middleware
func (sh *strictHandler) PressDoorbell(w http.ResponseWriter, r *http.Request, name string) {
	var request PressDoorbellRequestObject

	request.Name = name

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PressDoorbell(ctx, request.(PressDoorbellRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PressDoorbell")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PressDoorbellResponseObject); ok {
		if err := validResponse.VisitPressDoorbellResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SendPTZCommand operation middleware
func (sh *strictHandler) SendPTZCommand(w http.ResponseWriter, r *http.Request, name string) {
	var request SendPTZCommandRequestObject

	request.Name = name

	var body SendPTZCommandJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SendPTZCommand(ctx, request.(SendPTZCommandRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SendPTZCommand")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SendPTZCommandResponseObject); ok {
		if err := validResponse.VisitSendPTZCommandResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCameraSnapshot operation middleware
func (sh *strictHandler) GetCameraSnapshot(w http.ResponseWriter, r *http.Request, name string) {
	var request GetCameraSnapshotRequestObject

	request.Name = name

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCameraSnapshot(ctx, request.(GetCameraSnapshotRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCameraSnapshot")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCameraSnapshotResponseObject); ok {
		if err := validResponse.VisitGetCameraSnapshotResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCameraThumbnail operation middleware
func (sh *strictHandler) GetCameraThumbnail(w http.ResponseWriter, r *http.Request, name string, params GetCameraThumbnailParams) {
	var request GetCameraThumbnailRequestObject

	request.Name = name
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCameraThumbnail(ctx, request.(GetCameraThumbnailRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCameraThumbnail")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCameraThumbnailResponseObject); ok {
		if err := validResponse.VisitGetCameraThumbnailResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListZones operation middleware
func (sh *strictHandler) ListZones(w http.ResponseWriter, r *http.Request, name string) {
	var request ListZonesRequestObject

	request.Name = name

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListZones(ctx, request.(ListZonesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListZones")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListZonesResponseObject); ok {
		if err := validResponse.VisitListZonesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateZone operation middleware
func (sh *strictHandler) CreateZone(w http.ResponseWriter, r *http.Request, name string) {
	var request CreateZoneRequestObject

	request.Name = name

	var body CreateZoneJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateZone(ctx, request.(CreateZoneRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateZone")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateZoneResponseObject); ok {
		if err := validResponse.VisitCreateZoneResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteZone operation middleware
func (sh *strictHandler) DeleteZone(w http.ResponseWriter, r *http.Request, name string, zone string) {
	var request DeleteZoneRequestObject

	request.Name = name
	request.Zone = zone

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteZone(ctx, request.(DeleteZoneRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteZone")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteZoneResponseObject); ok {
		if err := validResponse.VisitDeleteZoneResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateZone operation middleware
func (sh *strictHandler) UpdateZone(w http.ResponseWriter, r *http.Request, name string, zone string) {
	var request UpdateZoneRequestObject

	request.Name = name
	request.Zone = zone

	var body UpdateZoneJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateZone(ctx, request.(UpdateZoneRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateZone")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateZoneResponseObject); ok {
		if err := validResponse.VisitUpdateZoneResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetZonePresence operation middleware
func (sh *strictHandler) GetZonePresence(w http.ResponseWriter, r *http.Request, name string, zone string) {
	var request GetZonePresenceRequestObject

	request.Name = name
	request.Zone = zone

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetZonePresence(ctx, request.(GetZonePresenceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetZonePresence")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetZonePresenceResponseObject); ok {
		if err := validResponse.VisitGetZonePresenceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealthLive operation middleware
func (sh *strictHandler) GetHealthLive(w http.ResponseWriter, r *http.Request) {
	var request GetHealthLiveRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthLive(ctx, request.(GetHealthLiveRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthLive")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthLiveResponseObject); ok {
		if err := validResponse.VisitGetHealthLiveResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealthReady operation middleware
func (sh *strictHandler) GetHealthReady(w http.ResponseWriter, r *http.Request) {
	var request GetHealthReadyRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthReady(ctx, request.(GetHealthReadyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthReady")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthReadyResponseObject); ok {
		if err := validResponse.VisitGetHealthReadyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOpenAPISpec operation middleware
func (sh *strictHandler) GetOpenAPISpec(w http.ResponseWriter, r *http.Request) {
	var request GetOpenAPISpecRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOpenAPISpec(ctx, request.(GetOpenAPISpecRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOpenAPISpec")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOpenAPISpecResponseObject); ok {
		if err := validResponse.VisitGetOpenAPISpecResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSystem operation middleware
func (sh *strictHandler) GetSystem(w http.ResponseWriter, r *http.Request) {
	var request GetSystemRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSystem(ctx, request.(GetSystemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSystem")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSystemResponseObject); ok {
		if err := validResponse.VisitGetSystemResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// TriggerRecompression operation middleware
func (sh *strictHandler) TriggerRecompression(w http.ResponseWriter, r *http.Request) {
	var request TriggerRecompressionRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.TriggerRecompression(ctx, request.(TriggerRecompressionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "TriggerRecompression")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(TriggerRecompressionResponseObject); ok {
		if err := validResponse.VisitTriggerRecompressionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateToken operation middleware
func (sh *strictHandler) CreateToken(w http.ResponseWriter, r *http.Request) {
	var request CreateTokenRequestObject

	var body CreateTokenJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateToken(ctx, request.(CreateTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateTokenResponseObject); ok {
		if err := validResponse.VisitCreateTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteToken operation middleware
func (sh *strictHandler) DeleteToken(w http.ResponseWriter, r *http.Request, id int64) {
	var request DeleteTokenRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteToken(ctx, request.(DeleteTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteToken")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteTokenResponseObject); ok {
		if err := validResponse.VisitDeleteTokenResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMetrics operation middleware
func (sh *strictHandler) GetMetrics(w http.ResponseWriter, r *http.Request) {
	var request GetMetricsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMetrics(ctx, request.(GetMetricsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMetrics")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMetricsResponseObject); ok {
		if err := validResponse.VisitGetMetricsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+Rb3XPbuBH/VzBsZ/rCi5xc2pnqLXXSnK+5RGO7eXDGo4HIFYWIBBgAlKN49L938MFv",
	"gKJiy1F6T7ZIYLEfPyx2F8v7IGJZzihQKYLpfSCiFWRY//uqkKs/4BJEzqgA9STnLAcuCej3keDLuWRr",
	"oOqX3OYQTAMhOaFJsAsD+JoTDmKOpXq9ZDxT/wUxlvCLJBkEYX/OmtDYSUxELDerEgmZcI6xDzDneKt+",
	"FwI4xRk4Bu/CgMOXgnCIg+mneqTloFrvtqLKFp8hkorsOc6A49cgMUn7Sokh4TiGphQLxlLAVM0t3845",
	"YMHcelthMc+YJK3XDRopFnK+5FawcXr1qCEMGE0JBfdCufzmfsEhYjxWFJyvvzEK84gVVDbeEyohAd5T",
	"vVW75aMlfa2uwDDTIt1kw2+m3wCncnW+gmjdt1VP+IrJMJBM4nQE/2ZcJYCfkwu6ZH0W9hn7MQ13iOYV",
	"Cb8s74iQb+gGUpaDTybuYa7av9U/f+WwDKbBXya1J5pYNzRp6M6xw1OSEem2H1suBciH2dZwGFY2NstV",
	"tMNaUqeqVpgmMMNC3DEeX8KXAoR0eNGCc6ByntuBTmtTuBsa0OG7R7JDwMktByzhWnlzL6teMB7unV1Y",
	"3MuW9yDSg+KDThoSt8YSKv/xsh7XAMsjCq2Q5Dst9Zt5zmFJvu63MNE2NRvY0OxQqNgLm9rxa/iGUfDa",
	"HShepL4jbYkjmCtXnFAydGgtID1QWV7N54zYaKXvTOxgWmQLu9m7Juj+5jhaK7UJoJHHZ3197iT99YXz",
	"8dY9eusaPXYfvGaMLyBNBzaB9pTuSGyjvAFxu5YcuDsS6bBWEQnLpaq5LobfcM64A0rl4z2L6WEuuo0D",
	"XfiUMPJUacYGKjbDEi+wUS3QIlN8sHUQ9pipdZd9kbI5PGKUQiR1wBIT0flpNpGLjpCM4wT2sX1lhrX4",
	"7iiuEsIyF1YqqVfxq/Ud2QzE+0JiWYiOelziFLn2unutbAlWE/yMXQKOtwPYr+AwpD5NxCJHK70rDlcD",
	"tKIwl4rhRgTal9MnjGVmSJiHydHaAk5BNGwHWB8wURhsgAsyxiN0Ja6nDlr0HUuIP8YYDIM4ZKD9ptNL",
	"f1e+NxgUWVZPIQF+SDLb4LPFlUdkVshDnEDKkgTiOSvk6E3iWnh2feMFBY7KyKJcNGMbMC4t12khy5ww",
	"jwmH3txCTYnZndJGCkudSpJkpf4S9WyUJJYllyTGz2i360k8HUWCB6Sejo3eZeZhx2VPoM5p2Q+uVSiI",
	"U/LNFzSOPPD0wvbUc593zZXC5ulXiubVSYts30JErOcpu9tTAJnnuBBuIXfOhZWQHITyklcSS4dNFlsJ",
	"QgXUKSYZjM1SBkN0XTHiBR3vhgQkmbKEDuwNx260duM2y4aPQtgTz2WfK+0lXkMK0qy6zwXFduhD/I9Z",
	"9MP6u+OeQ5bqxXFuAOINJqnSqHOX7cdohbX9G60HzJEw1yeT98iK59reo0DcP8bK2XaNsKuUhgoczHZV",
	"4LTEVkjI9iVVwu2nY4hYDHxcea4xr+H8fJnAAWp7nFiuF7nV4jVTiKpY2OZzOLew1ZsNW0N8SGDBzZQH",
	"bbUbRg/MlR9e6yCec/1nroG46k9VGaAMpQ1LlaA9ug4F1gr3WW/W4KptRb2MUzn6wIt0/TUef+jpWQLg",
	"gHPSiCYH7kHImGOzHGlVF9SE+1rRp3NUcCK3V8p726gBMAf+qpCr6hJPc6Mf15yvpMwVaxFjawLlcEKD",
	"qX1UWnMaCOs2a7Tk5D+wDXY7HeCZy4wYRMRJbvZC8Gp2gZaMowxTnBCaIOs4QqSLRyJElZMWIcI0RkYo",
	"FIM0YToiFMkVoI8Qg5QYvQd5x/gafSQxMHSpZwN/ppgiUh2LQTXy4yV6NbtoJKHT4OzZ82dn2hvnQHFO",
	"gmnwq36k0j650oqb4JxMcCFXE4OXX5oJaM5MNqJQhxV/F3Ew7RT2A2NKEPJfLN5q78KotKDAeZ6SSE+d",
	"fLZlNnPm7i1ROW8Pdm3kSF6AfmCcqhboxdnZozFRxUR63baxS9ZQuc92YfDyEdc2BUTHwh9xSmJNEYEd",
	"EwaiyDLMt5V1NIrsPQhSGfHfBGpch0icCJ3FqR1wqwjUOEhV0u+3vq4JHMnordLIE9u6Xetw6F0PQKKI",
	"IhBiWaTG4M+Pb/ALulEmRxGHGKhK93R0+vLFP4+/9iWWgPS9n0J4w/cG00+3TdgpX6qYi9SEOyJXqKzD",
	"aEc3HnuskIPgU++PC4Nm/ceNgwRipPho77w3NG5tu8YJMiCyiW8ScEj7FqTpQTmmwJ0uF4fA51aenBMa",
	"kRyniNj76CeB/3smEW6gK+6o/S3IltpbY2um/WZoJDlOM7wjQp5XKcDRDOFoLXAZQ49CKRFd+KmZCKcp",
	"qtOVUuCqGNSVeXKvduhuCIHn1WUX5jgDCVyRtEGTCiPqkMnGwW2fHTbE76Yxt0dXp21T8isytgMUmF8e",
	"H8x2VcokWrKCurActRgbb8RJbO9I/e5T5RKivEr9+UzauwR2KLgcY0JuZC//f6B9w+DvZ78+hZdEguJc",
	"rJS3rCpEbXRdc5IkwBFGJVSQrg4ZXR0CNdth5UbZFdB4dn1zzrIM6/uXY8Hs8QPQxiXMKaUa1zcoMtpE",
	"OIogl0+YbpTRp1U3YrzyUAyERroo8pxxiWbXN6fiSBUGEUZNzUmGMKpqNqOhXu6q/WfkVTnyBzlWkuEE",
	"Jp9zSNr6rUo5C0KVdvrlxJ52f5+9eVv5k1M6HFOygRJ/otb3aGvKVZEtqO1cHjbndTX0KPYMLZkvBWib",
	"WDpykMiYqtwPQEqt1af2SkoFqLLOKSG1KvXV2kFYIowSsgGKStuNBe43RmE4RbnRI04yqBvV6qyvKvqN",
	"sj3dq3E2/zkNa+vES9tHV38HD5nQV1OtulB/qnip3zw7Kmx6vKqBAY0HJK3g/4dUZk8DoMZKCGuQ7sfo",
	"kAea3Ks/O3P3kYKEPpRN38LxoBw6yXwz651Gotpu4PDBs+zaOBGUGHYtSnzOq3D4rv/mMf5ZDH4yLvDs",
	"aVxgoW3z53GBjBsn5wO5weoQyEd4v0mzU8CXRLTu7v+fHeHo4K7Sxtggr1QzEhJLODUoqSC/zaE9WvdC",
	"a6Ub34bAY1rjjnnb0GnFd6jBjEC2uagt+7+LNEVGDKS73xvyWum64k5U6r5f5ndkA8eXu/Whh0P2K+Ab",
	"EgEiAmHN99DVpyJGQQiUc7aAEZow31nsVcWl/Rzj6BhoflsyrAzD+SPXtA9nQ21Jy8qAXRRFMs4wtkHm",
	"Wcm4zzAfcqCvZhdXOUQPNUy3rakn7/UKkF0PiRwihAX6/erD+0GZmxPI0q7ekFx/lbUBvm0IL3QT6JDY",
	"pk30mFDsNKK6zK9H2Kvndq23fsOzrsA9UxtpJ3Vv7ESaaxH/hYa9N2k1CfeV8aLfENaagfRnVWUs1u3d",
	"kPBVTvIUEzdM/AW49ho41fsCEapAn6jHnkugDNMCp4h3hPLqTX8/Iwa6wuovlYNjRtqtT7SfuNrg+hrb",
	"tXPVgBOoPriLABTukHIR1XfT7q4IY+/JPYlHZPul2fdHuSQeV+D2dskfM293dmp7DVz2Z7f1bKYjTPcp",
	"OQPJSSSG/O4fdshekb/be8w4y0CuoBCo5KctjmOAy0m0j6R2P+6nW5WqNFtuP90qMwrgmxIpBU+DaTAJ",
	"1HNLvdddW/f1EEbDsr3KdtJWyhY11rSy1drO+F536UIGVIbVVZII0ez6JjTVXEM4rtslLNkyoO9TVkxU",
	"J6ydHRVqifJYsiTqY7hP5LdGWC1CJOrTzTBUm8ESs1bY3e7+FwAA//8ZTtUQzUgAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
